const Hero = () => {
  return (
    <div>PASIG RIVER AUTOMATED MONITORING SYSTEM (PRAMS): AN AUTOMATED WATER QUALITY MONITORING SYSTEM WITH WATER QUALITY INDEX (WQI) INTEGRATION</div>
  )
}

export default Hero